spring:
  application:
    name: uwu-study
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uwu?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: water123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: water123


  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:uwu}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
        register-enabled: ${NACOS_REGISTER_ENABLE:true}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: uwu
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:uwu-common.yaml
      - optional:nacos:uwu-study.yaml
server:
  port: 8889



rocketmq:
  name-server: 127.0.0.1:9876

  producer:
    group: uwu-water
    send-message-timeout: 3000
  multiTrigger:
    group: tmp-tem-multi-triger-group
    topic: tmp-tem-multi-triger-topic
  #阅信配置
  readingLetterPlus:
    group: dev-tem-readingLetter-group
    topic: dev-tem-readingLetter-topic
  aimprivatenumber:
    group: tmp-aimPrivateNumberGroup
    topic: tmp-aimPrivateNumberTopic

