spring:
  application:
    name: uwu-study
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:uwu}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
        register-enabled: ${NACOS_REGISTER_ENABLE:true}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: uwu
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:uwu-common.yaml
      - optional:nacos:uwu-study.yaml
server:
  port: 8012


