spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: uwu-study-db
  shardingsphere:
    datasource:
      names: m0
      m0: # 主表
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.109.44.114:3306/uwu_test_1?Encoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: Water123
    sharding:
      tables:
        customer:
          actual-data-nodes: m0.customer
          key-generator:
            column: customer_id
            type: SNOWFLAKE
          table-strategy: #分表
            standard: #支持范围查询
              sharding-column: customer_id
              range-algorithm-class-name: com.uwu.study.db.shardingspheredemo.algorithm.WaterRangeTablesShardingAlgorithm
              precise-algorithm-class-name: com.uwu.study.db.shardingspheredemo.algorithm.WaterPreciseTablesShardingAlgorithm
    props:
      sql:
        show: true
server:
  port: 8011