spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: uwu-study-db
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  redis:
    host: 47.109.44.114
    port: 6379
    database: 0
    timeout: 180000
    password: water123
    lettuce:
      pool:
        max-wait: -1 # 最大阻塞等待时间，负数表示没有限制
        max-idle: 5 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接
        max-active: 50 # 连接池中最大连接数，负数表示没有限制

  shardingsphere:
    mode: #不配置默认单机
      type: Standalone
      repository:
        type: JDBC
    datasource:
      names: m0
      m0: # 用户表
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.109.44.114:3306/uwu_test_1?Encoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: Water123
    rules:
      sharding:
        tables:
          customer:
            actual-data-nodes: m0.customer
            table-strategy: #分表
              standard: #支持范围查询
                sharding-column: customer_id
                sharding-algorithm-name: cspCustomer
        sharding-algorithms:
          cspCustomer:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.uwu.study.db.shardingspheredemo.shardingsphere521.algorithm.UserShardingAlgorithms

    props:
      sql:
        show: true
server:
  port: 8011