spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: uwu-study-db
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  redis:
    host: 47.109.44.114
    port: 6379
    database: 0
    timeout: 180000
    password: water123
    lettuce:
      pool:
        max-wait: -1 # 最大阻塞等待时间，负数表示没有限制
        max-idle: 5 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接
        max-active: 50 # 连接池中最大连接数，负数表示没有限制

  shardingsphere:
    mode: #不配置默认单机
      type: Standalone
      repository:
        type: JDBC
    datasource:
      names: m0
      m0: # 用户表
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.109.44.114:3306/uwu_test_1?Encoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: Water123
    rules:
      sharding:
        tables:
          customer:
            actual-data-nodes: m0.customer
            table-strategy: #分表
              standard: #支持范围查询
                sharding-column: customer_id
                sharding-algorithm-name: cspCustomer
        sharding-algorithms:
          cspCustomer:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.uwu.study.db.shardingspheredemo.shardingsphere521.algorithm.UserShardingAlgorithms

    props:
      sql-show: true
server:
  port: 8011

rocketmq:
  name-server: 47.109.44.114:9876
  producer:
    group: water-group
    send-message-timeout: 60000  # 发送消息超时时间，单位：毫秒。默认为 3000
    retry-times-when-send-failed: 3 # 同步发送消息时，失败重试次数。默认为 2 次
    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次
    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 默认为 false
    access-key: RocketMQAdmin # Access Key
    secret-key: 1qaz@WSX # Secret Key
    enable-msg-trace: true # 是否开启消息轨迹功能，默认为 true 开启
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义消息轨迹的 Topic,默认为 RMQ_SYS_TRACE_TOPIC
  consumer:
    access-key: RocketMQAdmin # Access Key
    secret-key: 1qaz@WSX # Secret Key